application:
  graph

resource:
  gpus: []
  cpu_per_gpu: auto
  dim: 128

graph:
  file_name: <friendster.small_graph>
  as_undirected: true

build:
  optimizer:
    type: SGD
    lr: 0.025
    weight_decay: 0.005
  num_partition: auto
  num_negative: 1
  batch_size: 100000
  episode_size: 3500

train:
  # here the best setting uses no augmentation
  # in this case, DeepWalk is equal to LINE
  model: DeepWalk
  num_epoch: 2000
  negative_weight: 5
  augmentation_step: 1
  random_walk_length: 40
  random_walk_batch_size: 100
  log_frequency: 1000

evaluate:
  task: node classification
  file_name: <friendster.label>
  portions: [0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.10]
  times: 5

save:
  file_name: deepwalk_friendster-small.pkl